### ISSUE TITLE
environment_min.yml is broken

### ISSUE THREAD

**Issue by basnijholt** [Microsoft/qmt#115]
I've just installed [this](https://github.com/Microsoft/qmt/blob/06e038970ba9fa63009d081d37abaecde3e146de/deployment/environment_min.yml) environment and it resulted in a broken `kwant`:
```
>>> import kwant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/w2scratch/home/t-banij/miniconda3/envs/py36/lib/python3.6/site-packages/kwant/__init__.py", line 37, in <module>
    exec('from . import {0}'.format(module))
  File "<string>", line 1, in <module>
  File "/w2scratch/home/t-banij/miniconda3/envs/py36/lib/python3.6/site-packages/kwant/builder.py", line 20, in <module>
    from .linalg import lll
  File "/w2scratch/home/t-banij/miniconda3/envs/py36/lib/python3.6/site-packages/kwant/linalg/__init__.py", line 10, in <module>
    from . import lapack
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

**Comment by basnijholt** [comment]
Ah, I only read these comments now https://github.com/Microsoft/qmt/blob/06e038970ba9fa63009d081d37abaecde3e146de/deployment/environment_min.yml#L1.

Should this or shouldn't it result in a correctly functioning env?

**Comment by basnijholt** [comment]
Unfortunately this also fails:
```
conda-env create -f environment_full_linux.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - matplotlib==2.2.2=py36_1
```

**Comment by likewei92** [comment]
When you install from environment_min, we're not version locking the packages, which means that you'll get the latest packages. Since package updates happen all the time, there's no way to know if this environment would work without testing it out. the environment_full files represent the last tested set of packages that are known to work. Normally I only use environment_min when I'm doing package upgrades. I install from that file, see what's working/not working, and if everything looks good I'll overwrite the environment_full files

**Comment by basnijholt** [comment]
OK great! Then I'll close this. We've also fixed what I mentioned [here](https://github.com/Microsoft/qmt/issues/115#issuecomment-485556375) by merging #116.
