### ISSUE TITLE
make the code PEP8 compliant

### ISSUE THREAD

**Issue by basnijholt** [Microsoft/qmt#23]
See [PEP8](https://www.python.org/dev/peps/pep-0008/?)

Right now I think the code violates every single "rule"  😜

**Comment by johnkgamble** [comment]
That's probably true; this isn't a priority since there are major (structural) changes happening frequently. Feel free to submit any stylistic improvements, but they might get clobbered!

**Comment by basnijholt** [comment]
I made a good start in https://github.com/Microsoft/qmt/pull/28.

**Comment by johnkgamble** [comment]
Bas, this is great! I’ll take a look to make sure nothing will have side effects on things other people are working on, but I think it’s good. Thanks for doing this!

**Comment by basnijholt** [comment]
Good to hear!

I am pretty sure that it will not change anything for anyone because I didn't change any API variable names 😄

**Comment by donjan** [comment]
- don't use just pep8, use pylint as well: it will be actually useful in fixing bugs instead of just cosmetics.
- a lot of the code is being touched in the fc017, and I'm generally peping+linting everything I write, so we have some duplication of effort. That's OK because some is not overlapping.
- merging master now will (depending on your schedule: continually) require some manual merging on my part (checked just briefly).
This is not your fault, but rather a strategic mistake (and nobody, including me, spoke up ;) ).

The last point I mention because generally it might be better to stick to the plan: work in feature branches. In this case won't matter because I will not be working on QMT this week and assume you won't make changes next week anymore, so just one big merge and no interference.

**Comment by basnijholt** [comment]
> don't use just pep8, use pylint as well: it will be actually useful in fixing bugs instead of just cosmetics.

With PEP8 I mean the actual Python [PEP](https://www.python.org/dev/peps/pep-0008/?) not a package. But I also used Flake8 (similar to `pylint`) and it pointed out some bugs that I fixed here.

**Comment by shreyasbapat** [comment]
Added #39 for this issue. I have made every python code PEP8 compliant. BTW, as you are using Travis, why don't you put up a code quality check as well?

**Comment by aeantipov** [comment]
This looks dated, reopen if needed
