### ISSUE TITLE
freecad_dict format

### ISSUE THREAD

**Issue by donjan** [Microsoft/qmt#35]
About the dictionary we use to feed Geometry3D.

### A

Recently we changed from `file_path` to `serial_fcdoc`. This means instead of
~~~~
freecad_dict = {
    'pyenv': 'python2',
    'file_path': 'geometry_sweep_showcase.fcstd'
}
~~~~
the user has to write
~~~~
freecad_dict = {
    'pyenv': 'python2',
    'serial_fcdoc': Geometry3D.serialize_fc_file('geometry_sweep_showcase.fcstd')
}
~~~~
1. Is the template doc required to be serialised? Might be a future proof choice in case it is not transfered on disk anymore, so I agree with that.
2. Is the doc required to be serialised by the user? We could call `serialize_fc_file` in the `Geometry3D.__init__`, then the user can write the more convenient top snippet.

On a related note, we have that kind of serialisation code in various places (`qmt/geometry/freecad/fileIO.py`, `qmt/data/geo_data.py` and now `qmt/tasks/geometry.py`). What would be a good place that is importable by Python2 and Python3, to hold a set of unified "deal with pipeable serial data" functions?

### B

The Geometry3D docstring states that the dict requires
~~~~
"parts_dict": parts_dict = {part_name: Part3D}
~~~~
The current implementation is
~~~~
"input_parts":input_parts_list = [Part3D]
~~~~

Since Geometry3D "consumes" (or is at least the sole user of) these parts, and the returned geo object contains the part names, why is there a need to set `part_name` at this point?

I plan to remove `parts_dict` and document `input_parts` as the build order spec.

**Comment by johnkgamble** [comment]
For point A - yes, it's required to be serialized. I actually changed this after many hours of debugging cryptic errors :). The problem was that all tests that had been run used a shared directory, which we don't want to assume using docker. Everything that a task needs we want to assume is either handed to it by previous task output (and is serializable) or is explicitly passed in through the options dictionary.

I agree with unifying the serialization routines and putting them somewhere. Perhaps in a new file in the data module? However, I think it's a good idea to (at this stage at least) require the user to explicitly serialize the data. The reason is that we want the options dictionary to really be the object that gets passed to _solve_instance. This makes debugging a lot easier. Maybe a compromise would be putting an explicit check to give a helpful error message if type str is passed in?

For B - I totally agree. part_name is obsolete now that the parts are objects. I noted this in a Todo when I noticed that wire shells actually targets parts now (rather than a str corresponding to the part name). Internally, I think that we always access the part_name's from the items in build_order, so it's important that the names of the step files correspond to the strings that are written in there. 

Perhaps an easy fix for now would just be to make the label field be automatically set by the name of the Part3DData class being instantiated? That way we wouldn't break any dependencies.

**Comment by donjan** [comment]
I'll deal with the unified serialisation tomorrow.

I disagree with the rationale behind requiring the user to serialise manually. The debugging is clear enough (you get an additional big blob attr quite early along the way instead of at the very beginning) and the difference in user convenience and "example niceness" is substantial IMO.
In case you're firm on this, I will add a more helpful error message. If a user gets the idea to put in a string despite the current variable naming and us only showing examples that manually call `serialize_fc_file`, the current error cryptically complains about padding. (then again, auto-serialising in the init preempts this ;) )

`Part3D.label` holds the pretty human-given name of each part at construction (in the user run.py). Each part knows it's own name.
This name is then added to `Geo3DData.build_order` during the construction of Geo3DData in the Geometry3D task, used as key in the `Geo3DData.parts` dict (since Kevin needs exactly that kind of access) and in the export naming.
The question about `part_name` and `parts_dict` here is resolved, the rest about build order pertains to #33.

**Comment by johnkgamble** [comment]
Looks good, thanks!
